workspace:
  metadata:
    distributions:
    - name: x64-generic
      triple: x86_64-unknown-linux-gnu
      cpu: x86-64-v3
      runner: ubuntu-latest
      docker:
        generic: true
        platform: linux/amd64

    - name: arm64-generic
      triple: aarch64-unknown-linux-gnu
      cpu: neoverse-v1
      docker:
        generic: true
        platform: linux/arm64

    - name: apple
      triple: aarch64-apple-darwin
      cpu: apple-latest
      runner: macos-latest
      docker: false

    - name: amd-zen4
      triple: x86_64-unknown-linux-gnu
      cpu: znver4
      docker:
        platform: linux/amd64
        generic: false

    - name: intel-xeon-gen4
      triple: x86_64-unknown-linux-gnu
      cpu: sapphirerapids
      docker:
        platform: linux/amd64
        generic: false

    - triple: aarch64-unknown-linux-gnu
      cpu: neoverse-v2
      name: aws-graviton4
      docker:
        generic: false
        platform: linux/arm64/v8