[package]
name = "laya"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

# Config for 'cargo dist'
[[workspace.metadata.distributions]]
name = "x64-generic"
triple = "x86_64-unknown-linux-gnu"
cpu = "x86-64-v3"
runner = "ubuntu-latest"
docker = "linux/amd64"
generic = true

[[workspace.metadata.distributions]]
name = "arm64-generic"
triple = "aarch64-unknown-linux-gnu"
cpu = "neoverse-v1"
generic = true
docker = "linux/arm64"

[[workspace.metadata.distributions]]
name = "apple"
triple = "aarch64-apple-darwin"
cpu = "apple-latest"
runner = "macos-latest"
generic = false
docker = false

[[workspace.metadata.distributions]]
name = "amd-zen4"
triple = "x86_64-unknown-linux-gnu"
cpu = "znver4"
generic = false
docker = "linux/amd64"

[[workspace.metadata.distributions]]
name = "intel-xeon-gen4"
triple = "x86_64-unknown-linux-gnu"
cpu = "sapphirerapids"
generic = false
docker = "linux/amd64"

[[workspace.metadata.distributions]]
triple = "aarch64-unknown-linux-gnu"
cpu = "neoverse-v2"
name = "aws-graviton4"
generic = false
docker = "linux/arm64/v8"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[features]
default = ["glommio", "rt-tokio"]
glommio = ["dep:glommio"]
rt-tokio = ["dep:tokio"]

[target.'cfg(linux)'.features]
default = ["glommio"]

[dependencies]
console-subscriber = { version = "0.4.0" }
clap = { version = "4.5.13", features = ["derive"] }
futures-lite = "1.13" # glommio requires 1.13.0
glommio = { version = "0.9.0", optional = true }
hyper = { version = "1.4.1", features = [
    "server",
    "http2",
    "http1",
    "tracing",
] }
hyper-util = { version = "0.1.6", features = [
    "server-auto",
    "server",
    "http2",
    "http1",
    "tokio",
] }
num_cpus = "1.16.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
once_cell = "1.19.0"
urlencoding = "2.1.3"
tokio = { version = "1.40", features = ["full", "tracing"], optional = true }
