[package]
name = "laya"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

# Config for 'cargo dist'
[[workspace.metadata.distributions]]
name = "x64-generic"
triple = "x86_64-unknown-linux-gnu"
cpu = "x86-64-v3"
runner = "ubuntu-latest"
docker = "linux/amd64"
generic = true

[[workspace.metadata.distributions]]
name = "arm64-generic"
triple = "aarch64-unknown-linux-gnu"
cpu = "neoverse-v1"
generic = true
docker = "linux/arm64"

[[workspace.metadata.distributions]]
name = "apple"
triple = "aarch64-apple-darwin"
cpu = "apple-latest"
runner = "macos-latest"
generic = true
docker = false

[[workspace.metadata.distributions]]
name = "amd-zen4"
triple = "x86_64-unknown-linux-gnu"
cpu = "znver4"
generic = false
docker = "linux/amd64"

[[workspace.metadata.distributions]]
name = "intel-xeon-gen4"
triple = "x86_64-unknown-linux-gnu"
cpu = "sapphirerapids"
generic = false
docker = "linux/amd64"

[[workspace.metadata.distributions]]
triple = "aarch64-unknown-linux-gnu"
cpu = "neoverse-v2"
name = "aws-graviton4"
generic = false
docker = "linux/arm64/v8"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[features]
default = ["rt-tokio"]
rt-tokio = ["dep:tokio"]
rt-glommio = []

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
http-body = { version = "1" }
http-body-util = { version = "0.1" }
hyper = { version = "1.4.1", features = [
    "server",
    "http2",
    "http1",
] }
hyper-util = { version = "0.1.6", features = [
    "server-auto",
    "server",
    "http2",
    "http1",
    "tokio",
] }
opentelemetry = { version = "0.26", features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.26", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-stdout = { version = "0.26", features = ["trace", "metrics"] }
opentelemetry-otlp = { version = "0.26", features = ["metrics"] }
opentelemetry-appender-tracing = "0.26.0"
opentelemetry-semantic-conventions = { version = "0.26", features = ["semconv_experimental"] }
num_cpus = "1.16.0"
tracing = "0.1.40"
tracing-opentelemetry = { version = "0.27" }
tracing-subscriber = "0.3.18"
once_cell = "1.19.0"
urlencoding = "2.1.3"
tokio = { version = "1.40", features = ["full"], optional = true }
