[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-pc-windows-gnu",
]
all-features = true

[licenses]
version = 2
allow = ["Apache-2.0", "BSD-2-Clause", "MIT", "Unlicense", "Zlib"]

exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]

[bans]
multiple-versions = "warn"
wildcards = "deny"
skip = [
    { crate = "sync_wrapper@0.1.2", reason = "used by tower and opentelemetry-http" },
]
[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
