[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-pc-windows-gnu",
]
all-features = true

[advisories]
# The path where the advisory databases are cloned/fetched into
#db-path = "$CARGO_HOME/advisory-dbs"
# The url(s) of the advisory databases to use
#db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
    #"RUSTSEC-0000-0000",
    #"a-crate-that-is-yanked@0.1.1", # you can also ignore yanked crate versions if you wish
    #{ crate = "a-crate-that-is-yanked@0.1.1", reason = "you can specify why you are ignoring the yanked crate" },
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Zlib",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "MPL-2.0",
    "IJG",
]


exceptions = [
    { name = "tracing-opentelemetry-instrumentation-sdk", allow = [
        "CC0-1.0",
    ] },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

skip = [
    { crate = "windows-sys", reason = "included in thousands of crates" },
]

skip-tree = ["thiserror"]


[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/digirati-co-uk/kaduceus"]
