name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_REGISTRIES_DLCS_INDEX: "sparse+https://dlcs-spinup-167865917244.d.codeartifact.eu-west-1.amazonaws.com/cargo/private/"
  CARGO_REGISTRIES_DLCS_CREDENTIAL_PROVIDER: "cargo:token-from-stdout aws codeartifact get-authorization-token --domain dlcs-spinup --domain-owner 167865917244 --region eu-west-1 --query authorizationToken --output text"
    
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    permissions:
      id-token: write    
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: true

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.KAKADU_SSH_KEY }}
          repository: digirati-co-uk/kakadu
          path: kakadu
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::167865917244:role/Delegated_DLCSDev_GitHubActions_CI_retags
          aws-region: eu-west-1          
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all
        env:
          CARGO_INCREMENTAL: 0
      - name: Test
        run: cargo test --all

  cargo-deny:
    name: Check dependencies
    runs-on: ubuntu-24.04
    permissions:
      id-token: write    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::167865917244:role/Delegated_DLCSDev_GitHubActions_CI_retags
          aws-region: eu-west-1          
      - uses: EmbarkStudios/cargo-deny-action@v2

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: true

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.KAKADU_SSH_KEY }}
          repository: digirati-co-uk/kakadu
          path: kakadu
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::167865917244:role/Delegated_DLCSDev_GitHubActions_CI_retags
          aws-region: eu-west-1          
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --workspace --all-targets --all-features -- -Aunused

  fmt:
    name: Formatting
    runs-on: ubuntu-24.04
    permissions:
      id-token: write    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: true

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.KAKADU_SSH_KEY }}
          repository: digirati-co-uk/kakadu
          path: kakadu
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::167865917244:role/Delegated_DLCSDev_GitHubActions_CI_retags
          aws-region: eu-west-1          
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --all --check
